// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AppendEntries.proto

package com.reber.raft;

public final class AppendEntriesProtos {
  private AppendEntriesProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AppendEntriesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:raft.AppendEntries)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 term = 1;</code>
     */
    boolean hasTerm();
    /**
     * <code>optional int32 term = 1;</code>
     */
    int getTerm();

    /**
     * <code>optional string leaderId = 2;</code>
     */
    boolean hasLeaderId();
    /**
     * <code>optional string leaderId = 2;</code>
     */
    java.lang.String getLeaderId();
    /**
     * <code>optional string leaderId = 2;</code>
     */
    com.google.protobuf.ByteString
        getLeaderIdBytes();

    /**
     * <code>optional int32 prevLogIndex = 3;</code>
     */
    boolean hasPrevLogIndex();
    /**
     * <code>optional int32 prevLogIndex = 3;</code>
     */
    int getPrevLogIndex();

    /**
     * <code>optional int32 prevLogterm = 4;</code>
     */
    boolean hasPrevLogterm();
    /**
     * <code>optional int32 prevLogterm = 4;</code>
     */
    int getPrevLogterm();

    /**
     * <code>optional int32 leaderCommit = 5;</code>
     */
    boolean hasLeaderCommit();
    /**
     * <code>optional int32 leaderCommit = 5;</code>
     */
    int getLeaderCommit();

    /**
     * <code>repeated .raft.AppendEntries.Entry entries = 6;</code>
     */
    java.util.List<com.reber.raft.AppendEntriesProtos.AppendEntries.Entry> 
        getEntriesList();
    /**
     * <code>repeated .raft.AppendEntries.Entry entries = 6;</code>
     */
    com.reber.raft.AppendEntriesProtos.AppendEntries.Entry getEntries(int index);
    /**
     * <code>repeated .raft.AppendEntries.Entry entries = 6;</code>
     */
    int getEntriesCount();
    /**
     * <code>repeated .raft.AppendEntries.Entry entries = 6;</code>
     */
    java.util.List<? extends com.reber.raft.AppendEntriesProtos.AppendEntries.EntryOrBuilder> 
        getEntriesOrBuilderList();
    /**
     * <code>repeated .raft.AppendEntries.Entry entries = 6;</code>
     */
    com.reber.raft.AppendEntriesProtos.AppendEntries.EntryOrBuilder getEntriesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code raft.AppendEntries}
   */
  public  static final class AppendEntries extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:raft.AppendEntries)
      AppendEntriesOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AppendEntries.newBuilder() to construct.
    private AppendEntries(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AppendEntries() {
      term_ = 0;
      leaderId_ = "";
      prevLogIndex_ = 0;
      prevLogterm_ = 0;
      leaderCommit_ = 0;
      entries_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AppendEntries(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              term_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              leaderId_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              prevLogIndex_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              prevLogterm_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              leaderCommit_ = input.readInt32();
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                entries_ = new java.util.ArrayList<com.reber.raft.AppendEntriesProtos.AppendEntries.Entry>();
                mutable_bitField0_ |= 0x00000020;
              }
              entries_.add(
                  input.readMessage(com.reber.raft.AppendEntriesProtos.AppendEntries.Entry.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          entries_ = java.util.Collections.unmodifiableList(entries_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.reber.raft.AppendEntriesProtos.internal_static_raft_AppendEntries_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.reber.raft.AppendEntriesProtos.internal_static_raft_AppendEntries_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.reber.raft.AppendEntriesProtos.AppendEntries.class, com.reber.raft.AppendEntriesProtos.AppendEntries.Builder.class);
    }

    public interface EntryOrBuilder extends
        // @@protoc_insertion_point(interface_extends:raft.AppendEntries.Entry)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional int32 termNumber = 1;</code>
       */
      boolean hasTermNumber();
      /**
       * <code>optional int32 termNumber = 1;</code>
       */
      int getTermNumber();

      /**
       * <code>optional string message = 2;</code>
       */
      boolean hasMessage();
      /**
       * <code>optional string message = 2;</code>
       */
      java.lang.String getMessage();
      /**
       * <code>optional string message = 2;</code>
       */
      com.google.protobuf.ByteString
          getMessageBytes();
    }
    /**
     * Protobuf type {@code raft.AppendEntries.Entry}
     */
    public  static final class Entry extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:raft.AppendEntries.Entry)
        EntryOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Entry.newBuilder() to construct.
      private Entry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Entry() {
        termNumber_ = 0;
        message_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Entry(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                termNumber_ = input.readInt32();
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                message_ = bs;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.reber.raft.AppendEntriesProtos.internal_static_raft_AppendEntries_Entry_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.reber.raft.AppendEntriesProtos.internal_static_raft_AppendEntries_Entry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.reber.raft.AppendEntriesProtos.AppendEntries.Entry.class, com.reber.raft.AppendEntriesProtos.AppendEntries.Entry.Builder.class);
      }

      private int bitField0_;
      public static final int TERMNUMBER_FIELD_NUMBER = 1;
      private int termNumber_;
      /**
       * <code>optional int32 termNumber = 1;</code>
       */
      public boolean hasTermNumber() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 termNumber = 1;</code>
       */
      public int getTermNumber() {
        return termNumber_;
      }

      public static final int MESSAGE_FIELD_NUMBER = 2;
      private volatile java.lang.Object message_;
      /**
       * <code>optional string message = 2;</code>
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string message = 2;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            message_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string message = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, termNumber_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, termNumber_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.reber.raft.AppendEntriesProtos.AppendEntries.Entry)) {
          return super.equals(obj);
        }
        com.reber.raft.AppendEntriesProtos.AppendEntries.Entry other = (com.reber.raft.AppendEntriesProtos.AppendEntries.Entry) obj;

        boolean result = true;
        result = result && (hasTermNumber() == other.hasTermNumber());
        if (hasTermNumber()) {
          result = result && (getTermNumber()
              == other.getTermNumber());
        }
        result = result && (hasMessage() == other.hasMessage());
        if (hasMessage()) {
          result = result && getMessage()
              .equals(other.getMessage());
        }
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasTermNumber()) {
          hash = (37 * hash) + TERMNUMBER_FIELD_NUMBER;
          hash = (53 * hash) + getTermNumber();
        }
        if (hasMessage()) {
          hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
          hash = (53 * hash) + getMessage().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.reber.raft.AppendEntriesProtos.AppendEntries.Entry parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.reber.raft.AppendEntriesProtos.AppendEntries.Entry parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.reber.raft.AppendEntriesProtos.AppendEntries.Entry parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.reber.raft.AppendEntriesProtos.AppendEntries.Entry parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.reber.raft.AppendEntriesProtos.AppendEntries.Entry parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.reber.raft.AppendEntriesProtos.AppendEntries.Entry parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.reber.raft.AppendEntriesProtos.AppendEntries.Entry parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.reber.raft.AppendEntriesProtos.AppendEntries.Entry parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.reber.raft.AppendEntriesProtos.AppendEntries.Entry parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.reber.raft.AppendEntriesProtos.AppendEntries.Entry parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.reber.raft.AppendEntriesProtos.AppendEntries.Entry parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.reber.raft.AppendEntriesProtos.AppendEntries.Entry parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.reber.raft.AppendEntriesProtos.AppendEntries.Entry prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code raft.AppendEntries.Entry}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:raft.AppendEntries.Entry)
          com.reber.raft.AppendEntriesProtos.AppendEntries.EntryOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.reber.raft.AppendEntriesProtos.internal_static_raft_AppendEntries_Entry_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.reber.raft.AppendEntriesProtos.internal_static_raft_AppendEntries_Entry_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.reber.raft.AppendEntriesProtos.AppendEntries.Entry.class, com.reber.raft.AppendEntriesProtos.AppendEntries.Entry.Builder.class);
        }

        // Construct using com.reber.raft.AppendEntriesProtos.AppendEntries.Entry.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          termNumber_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          message_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.reber.raft.AppendEntriesProtos.internal_static_raft_AppendEntries_Entry_descriptor;
        }

        public com.reber.raft.AppendEntriesProtos.AppendEntries.Entry getDefaultInstanceForType() {
          return com.reber.raft.AppendEntriesProtos.AppendEntries.Entry.getDefaultInstance();
        }

        public com.reber.raft.AppendEntriesProtos.AppendEntries.Entry build() {
          com.reber.raft.AppendEntriesProtos.AppendEntries.Entry result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.reber.raft.AppendEntriesProtos.AppendEntries.Entry buildPartial() {
          com.reber.raft.AppendEntriesProtos.AppendEntries.Entry result = new com.reber.raft.AppendEntriesProtos.AppendEntries.Entry(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.termNumber_ = termNumber_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.message_ = message_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.reber.raft.AppendEntriesProtos.AppendEntries.Entry) {
            return mergeFrom((com.reber.raft.AppendEntriesProtos.AppendEntries.Entry)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.reber.raft.AppendEntriesProtos.AppendEntries.Entry other) {
          if (other == com.reber.raft.AppendEntriesProtos.AppendEntries.Entry.getDefaultInstance()) return this;
          if (other.hasTermNumber()) {
            setTermNumber(other.getTermNumber());
          }
          if (other.hasMessage()) {
            bitField0_ |= 0x00000002;
            message_ = other.message_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.reber.raft.AppendEntriesProtos.AppendEntries.Entry parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.reber.raft.AppendEntriesProtos.AppendEntries.Entry) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int termNumber_ ;
        /**
         * <code>optional int32 termNumber = 1;</code>
         */
        public boolean hasTermNumber() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional int32 termNumber = 1;</code>
         */
        public int getTermNumber() {
          return termNumber_;
        }
        /**
         * <code>optional int32 termNumber = 1;</code>
         */
        public Builder setTermNumber(int value) {
          bitField0_ |= 0x00000001;
          termNumber_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 termNumber = 1;</code>
         */
        public Builder clearTermNumber() {
          bitField0_ = (bitField0_ & ~0x00000001);
          termNumber_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object message_ = "";
        /**
         * <code>optional string message = 2;</code>
         */
        public boolean hasMessage() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string message = 2;</code>
         */
        public java.lang.String getMessage() {
          java.lang.Object ref = message_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              message_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string message = 2;</code>
         */
        public com.google.protobuf.ByteString
            getMessageBytes() {
          java.lang.Object ref = message_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            message_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string message = 2;</code>
         */
        public Builder setMessage(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          message_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string message = 2;</code>
         */
        public Builder clearMessage() {
          bitField0_ = (bitField0_ & ~0x00000002);
          message_ = getDefaultInstance().getMessage();
          onChanged();
          return this;
        }
        /**
         * <code>optional string message = 2;</code>
         */
        public Builder setMessageBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          message_ = value;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:raft.AppendEntries.Entry)
      }

      // @@protoc_insertion_point(class_scope:raft.AppendEntries.Entry)
      private static final com.reber.raft.AppendEntriesProtos.AppendEntries.Entry DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.reber.raft.AppendEntriesProtos.AppendEntries.Entry();
      }

      public static com.reber.raft.AppendEntriesProtos.AppendEntries.Entry getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<Entry>
          PARSER = new com.google.protobuf.AbstractParser<Entry>() {
        public Entry parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Entry(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Entry> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Entry> getParserForType() {
        return PARSER;
      }

      public com.reber.raft.AppendEntriesProtos.AppendEntries.Entry getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int TERM_FIELD_NUMBER = 1;
    private int term_;
    /**
     * <code>optional int32 term = 1;</code>
     */
    public boolean hasTerm() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 term = 1;</code>
     */
    public int getTerm() {
      return term_;
    }

    public static final int LEADERID_FIELD_NUMBER = 2;
    private volatile java.lang.Object leaderId_;
    /**
     * <code>optional string leaderId = 2;</code>
     */
    public boolean hasLeaderId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string leaderId = 2;</code>
     */
    public java.lang.String getLeaderId() {
      java.lang.Object ref = leaderId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          leaderId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string leaderId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLeaderIdBytes() {
      java.lang.Object ref = leaderId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        leaderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PREVLOGINDEX_FIELD_NUMBER = 3;
    private int prevLogIndex_;
    /**
     * <code>optional int32 prevLogIndex = 3;</code>
     */
    public boolean hasPrevLogIndex() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 prevLogIndex = 3;</code>
     */
    public int getPrevLogIndex() {
      return prevLogIndex_;
    }

    public static final int PREVLOGTERM_FIELD_NUMBER = 4;
    private int prevLogterm_;
    /**
     * <code>optional int32 prevLogterm = 4;</code>
     */
    public boolean hasPrevLogterm() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 prevLogterm = 4;</code>
     */
    public int getPrevLogterm() {
      return prevLogterm_;
    }

    public static final int LEADERCOMMIT_FIELD_NUMBER = 5;
    private int leaderCommit_;
    /**
     * <code>optional int32 leaderCommit = 5;</code>
     */
    public boolean hasLeaderCommit() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 leaderCommit = 5;</code>
     */
    public int getLeaderCommit() {
      return leaderCommit_;
    }

    public static final int ENTRIES_FIELD_NUMBER = 6;
    private java.util.List<com.reber.raft.AppendEntriesProtos.AppendEntries.Entry> entries_;
    /**
     * <code>repeated .raft.AppendEntries.Entry entries = 6;</code>
     */
    public java.util.List<com.reber.raft.AppendEntriesProtos.AppendEntries.Entry> getEntriesList() {
      return entries_;
    }
    /**
     * <code>repeated .raft.AppendEntries.Entry entries = 6;</code>
     */
    public java.util.List<? extends com.reber.raft.AppendEntriesProtos.AppendEntries.EntryOrBuilder> 
        getEntriesOrBuilderList() {
      return entries_;
    }
    /**
     * <code>repeated .raft.AppendEntries.Entry entries = 6;</code>
     */
    public int getEntriesCount() {
      return entries_.size();
    }
    /**
     * <code>repeated .raft.AppendEntries.Entry entries = 6;</code>
     */
    public com.reber.raft.AppendEntriesProtos.AppendEntries.Entry getEntries(int index) {
      return entries_.get(index);
    }
    /**
     * <code>repeated .raft.AppendEntries.Entry entries = 6;</code>
     */
    public com.reber.raft.AppendEntriesProtos.AppendEntries.EntryOrBuilder getEntriesOrBuilder(
        int index) {
      return entries_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, term_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, leaderId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, prevLogIndex_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, prevLogterm_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, leaderCommit_);
      }
      for (int i = 0; i < entries_.size(); i++) {
        output.writeMessage(6, entries_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, term_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, leaderId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, prevLogIndex_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, prevLogterm_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, leaderCommit_);
      }
      for (int i = 0; i < entries_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, entries_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.reber.raft.AppendEntriesProtos.AppendEntries)) {
        return super.equals(obj);
      }
      com.reber.raft.AppendEntriesProtos.AppendEntries other = (com.reber.raft.AppendEntriesProtos.AppendEntries) obj;

      boolean result = true;
      result = result && (hasTerm() == other.hasTerm());
      if (hasTerm()) {
        result = result && (getTerm()
            == other.getTerm());
      }
      result = result && (hasLeaderId() == other.hasLeaderId());
      if (hasLeaderId()) {
        result = result && getLeaderId()
            .equals(other.getLeaderId());
      }
      result = result && (hasPrevLogIndex() == other.hasPrevLogIndex());
      if (hasPrevLogIndex()) {
        result = result && (getPrevLogIndex()
            == other.getPrevLogIndex());
      }
      result = result && (hasPrevLogterm() == other.hasPrevLogterm());
      if (hasPrevLogterm()) {
        result = result && (getPrevLogterm()
            == other.getPrevLogterm());
      }
      result = result && (hasLeaderCommit() == other.hasLeaderCommit());
      if (hasLeaderCommit()) {
        result = result && (getLeaderCommit()
            == other.getLeaderCommit());
      }
      result = result && getEntriesList()
          .equals(other.getEntriesList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTerm()) {
        hash = (37 * hash) + TERM_FIELD_NUMBER;
        hash = (53 * hash) + getTerm();
      }
      if (hasLeaderId()) {
        hash = (37 * hash) + LEADERID_FIELD_NUMBER;
        hash = (53 * hash) + getLeaderId().hashCode();
      }
      if (hasPrevLogIndex()) {
        hash = (37 * hash) + PREVLOGINDEX_FIELD_NUMBER;
        hash = (53 * hash) + getPrevLogIndex();
      }
      if (hasPrevLogterm()) {
        hash = (37 * hash) + PREVLOGTERM_FIELD_NUMBER;
        hash = (53 * hash) + getPrevLogterm();
      }
      if (hasLeaderCommit()) {
        hash = (37 * hash) + LEADERCOMMIT_FIELD_NUMBER;
        hash = (53 * hash) + getLeaderCommit();
      }
      if (getEntriesCount() > 0) {
        hash = (37 * hash) + ENTRIES_FIELD_NUMBER;
        hash = (53 * hash) + getEntriesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.reber.raft.AppendEntriesProtos.AppendEntries parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reber.raft.AppendEntriesProtos.AppendEntries parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reber.raft.AppendEntriesProtos.AppendEntries parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reber.raft.AppendEntriesProtos.AppendEntries parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reber.raft.AppendEntriesProtos.AppendEntries parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reber.raft.AppendEntriesProtos.AppendEntries parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reber.raft.AppendEntriesProtos.AppendEntries parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.reber.raft.AppendEntriesProtos.AppendEntries parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.reber.raft.AppendEntriesProtos.AppendEntries parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.reber.raft.AppendEntriesProtos.AppendEntries parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.reber.raft.AppendEntriesProtos.AppendEntries parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.reber.raft.AppendEntriesProtos.AppendEntries parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.reber.raft.AppendEntriesProtos.AppendEntries prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code raft.AppendEntries}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:raft.AppendEntries)
        com.reber.raft.AppendEntriesProtos.AppendEntriesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.reber.raft.AppendEntriesProtos.internal_static_raft_AppendEntries_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.reber.raft.AppendEntriesProtos.internal_static_raft_AppendEntries_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.reber.raft.AppendEntriesProtos.AppendEntries.class, com.reber.raft.AppendEntriesProtos.AppendEntries.Builder.class);
      }

      // Construct using com.reber.raft.AppendEntriesProtos.AppendEntries.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getEntriesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        term_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        leaderId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        prevLogIndex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        prevLogterm_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        leaderCommit_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        if (entriesBuilder_ == null) {
          entries_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          entriesBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.reber.raft.AppendEntriesProtos.internal_static_raft_AppendEntries_descriptor;
      }

      public com.reber.raft.AppendEntriesProtos.AppendEntries getDefaultInstanceForType() {
        return com.reber.raft.AppendEntriesProtos.AppendEntries.getDefaultInstance();
      }

      public com.reber.raft.AppendEntriesProtos.AppendEntries build() {
        com.reber.raft.AppendEntriesProtos.AppendEntries result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.reber.raft.AppendEntriesProtos.AppendEntries buildPartial() {
        com.reber.raft.AppendEntriesProtos.AppendEntries result = new com.reber.raft.AppendEntriesProtos.AppendEntries(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.term_ = term_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.leaderId_ = leaderId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.prevLogIndex_ = prevLogIndex_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.prevLogterm_ = prevLogterm_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.leaderCommit_ = leaderCommit_;
        if (entriesBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020)) {
            entries_ = java.util.Collections.unmodifiableList(entries_);
            bitField0_ = (bitField0_ & ~0x00000020);
          }
          result.entries_ = entries_;
        } else {
          result.entries_ = entriesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.reber.raft.AppendEntriesProtos.AppendEntries) {
          return mergeFrom((com.reber.raft.AppendEntriesProtos.AppendEntries)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.reber.raft.AppendEntriesProtos.AppendEntries other) {
        if (other == com.reber.raft.AppendEntriesProtos.AppendEntries.getDefaultInstance()) return this;
        if (other.hasTerm()) {
          setTerm(other.getTerm());
        }
        if (other.hasLeaderId()) {
          bitField0_ |= 0x00000002;
          leaderId_ = other.leaderId_;
          onChanged();
        }
        if (other.hasPrevLogIndex()) {
          setPrevLogIndex(other.getPrevLogIndex());
        }
        if (other.hasPrevLogterm()) {
          setPrevLogterm(other.getPrevLogterm());
        }
        if (other.hasLeaderCommit()) {
          setLeaderCommit(other.getLeaderCommit());
        }
        if (entriesBuilder_ == null) {
          if (!other.entries_.isEmpty()) {
            if (entries_.isEmpty()) {
              entries_ = other.entries_;
              bitField0_ = (bitField0_ & ~0x00000020);
            } else {
              ensureEntriesIsMutable();
              entries_.addAll(other.entries_);
            }
            onChanged();
          }
        } else {
          if (!other.entries_.isEmpty()) {
            if (entriesBuilder_.isEmpty()) {
              entriesBuilder_.dispose();
              entriesBuilder_ = null;
              entries_ = other.entries_;
              bitField0_ = (bitField0_ & ~0x00000020);
              entriesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getEntriesFieldBuilder() : null;
            } else {
              entriesBuilder_.addAllMessages(other.entries_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.reber.raft.AppendEntriesProtos.AppendEntries parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.reber.raft.AppendEntriesProtos.AppendEntries) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int term_ ;
      /**
       * <code>optional int32 term = 1;</code>
       */
      public boolean hasTerm() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 term = 1;</code>
       */
      public int getTerm() {
        return term_;
      }
      /**
       * <code>optional int32 term = 1;</code>
       */
      public Builder setTerm(int value) {
        bitField0_ |= 0x00000001;
        term_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 term = 1;</code>
       */
      public Builder clearTerm() {
        bitField0_ = (bitField0_ & ~0x00000001);
        term_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object leaderId_ = "";
      /**
       * <code>optional string leaderId = 2;</code>
       */
      public boolean hasLeaderId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string leaderId = 2;</code>
       */
      public java.lang.String getLeaderId() {
        java.lang.Object ref = leaderId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            leaderId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string leaderId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLeaderIdBytes() {
        java.lang.Object ref = leaderId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          leaderId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string leaderId = 2;</code>
       */
      public Builder setLeaderId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        leaderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string leaderId = 2;</code>
       */
      public Builder clearLeaderId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        leaderId_ = getDefaultInstance().getLeaderId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string leaderId = 2;</code>
       */
      public Builder setLeaderIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        leaderId_ = value;
        onChanged();
        return this;
      }

      private int prevLogIndex_ ;
      /**
       * <code>optional int32 prevLogIndex = 3;</code>
       */
      public boolean hasPrevLogIndex() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 prevLogIndex = 3;</code>
       */
      public int getPrevLogIndex() {
        return prevLogIndex_;
      }
      /**
       * <code>optional int32 prevLogIndex = 3;</code>
       */
      public Builder setPrevLogIndex(int value) {
        bitField0_ |= 0x00000004;
        prevLogIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 prevLogIndex = 3;</code>
       */
      public Builder clearPrevLogIndex() {
        bitField0_ = (bitField0_ & ~0x00000004);
        prevLogIndex_ = 0;
        onChanged();
        return this;
      }

      private int prevLogterm_ ;
      /**
       * <code>optional int32 prevLogterm = 4;</code>
       */
      public boolean hasPrevLogterm() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 prevLogterm = 4;</code>
       */
      public int getPrevLogterm() {
        return prevLogterm_;
      }
      /**
       * <code>optional int32 prevLogterm = 4;</code>
       */
      public Builder setPrevLogterm(int value) {
        bitField0_ |= 0x00000008;
        prevLogterm_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 prevLogterm = 4;</code>
       */
      public Builder clearPrevLogterm() {
        bitField0_ = (bitField0_ & ~0x00000008);
        prevLogterm_ = 0;
        onChanged();
        return this;
      }

      private int leaderCommit_ ;
      /**
       * <code>optional int32 leaderCommit = 5;</code>
       */
      public boolean hasLeaderCommit() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 leaderCommit = 5;</code>
       */
      public int getLeaderCommit() {
        return leaderCommit_;
      }
      /**
       * <code>optional int32 leaderCommit = 5;</code>
       */
      public Builder setLeaderCommit(int value) {
        bitField0_ |= 0x00000010;
        leaderCommit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 leaderCommit = 5;</code>
       */
      public Builder clearLeaderCommit() {
        bitField0_ = (bitField0_ & ~0x00000010);
        leaderCommit_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.reber.raft.AppendEntriesProtos.AppendEntries.Entry> entries_ =
        java.util.Collections.emptyList();
      private void ensureEntriesIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          entries_ = new java.util.ArrayList<com.reber.raft.AppendEntriesProtos.AppendEntries.Entry>(entries_);
          bitField0_ |= 0x00000020;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.reber.raft.AppendEntriesProtos.AppendEntries.Entry, com.reber.raft.AppendEntriesProtos.AppendEntries.Entry.Builder, com.reber.raft.AppendEntriesProtos.AppendEntries.EntryOrBuilder> entriesBuilder_;

      /**
       * <code>repeated .raft.AppendEntries.Entry entries = 6;</code>
       */
      public java.util.List<com.reber.raft.AppendEntriesProtos.AppendEntries.Entry> getEntriesList() {
        if (entriesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(entries_);
        } else {
          return entriesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .raft.AppendEntries.Entry entries = 6;</code>
       */
      public int getEntriesCount() {
        if (entriesBuilder_ == null) {
          return entries_.size();
        } else {
          return entriesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .raft.AppendEntries.Entry entries = 6;</code>
       */
      public com.reber.raft.AppendEntriesProtos.AppendEntries.Entry getEntries(int index) {
        if (entriesBuilder_ == null) {
          return entries_.get(index);
        } else {
          return entriesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .raft.AppendEntries.Entry entries = 6;</code>
       */
      public Builder setEntries(
          int index, com.reber.raft.AppendEntriesProtos.AppendEntries.Entry value) {
        if (entriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntriesIsMutable();
          entries_.set(index, value);
          onChanged();
        } else {
          entriesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .raft.AppendEntries.Entry entries = 6;</code>
       */
      public Builder setEntries(
          int index, com.reber.raft.AppendEntriesProtos.AppendEntries.Entry.Builder builderForValue) {
        if (entriesBuilder_ == null) {
          ensureEntriesIsMutable();
          entries_.set(index, builderForValue.build());
          onChanged();
        } else {
          entriesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .raft.AppendEntries.Entry entries = 6;</code>
       */
      public Builder addEntries(com.reber.raft.AppendEntriesProtos.AppendEntries.Entry value) {
        if (entriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntriesIsMutable();
          entries_.add(value);
          onChanged();
        } else {
          entriesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .raft.AppendEntries.Entry entries = 6;</code>
       */
      public Builder addEntries(
          int index, com.reber.raft.AppendEntriesProtos.AppendEntries.Entry value) {
        if (entriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntriesIsMutable();
          entries_.add(index, value);
          onChanged();
        } else {
          entriesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .raft.AppendEntries.Entry entries = 6;</code>
       */
      public Builder addEntries(
          com.reber.raft.AppendEntriesProtos.AppendEntries.Entry.Builder builderForValue) {
        if (entriesBuilder_ == null) {
          ensureEntriesIsMutable();
          entries_.add(builderForValue.build());
          onChanged();
        } else {
          entriesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .raft.AppendEntries.Entry entries = 6;</code>
       */
      public Builder addEntries(
          int index, com.reber.raft.AppendEntriesProtos.AppendEntries.Entry.Builder builderForValue) {
        if (entriesBuilder_ == null) {
          ensureEntriesIsMutable();
          entries_.add(index, builderForValue.build());
          onChanged();
        } else {
          entriesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .raft.AppendEntries.Entry entries = 6;</code>
       */
      public Builder addAllEntries(
          java.lang.Iterable<? extends com.reber.raft.AppendEntriesProtos.AppendEntries.Entry> values) {
        if (entriesBuilder_ == null) {
          ensureEntriesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, entries_);
          onChanged();
        } else {
          entriesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .raft.AppendEntries.Entry entries = 6;</code>
       */
      public Builder clearEntries() {
        if (entriesBuilder_ == null) {
          entries_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
          onChanged();
        } else {
          entriesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .raft.AppendEntries.Entry entries = 6;</code>
       */
      public Builder removeEntries(int index) {
        if (entriesBuilder_ == null) {
          ensureEntriesIsMutable();
          entries_.remove(index);
          onChanged();
        } else {
          entriesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .raft.AppendEntries.Entry entries = 6;</code>
       */
      public com.reber.raft.AppendEntriesProtos.AppendEntries.Entry.Builder getEntriesBuilder(
          int index) {
        return getEntriesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .raft.AppendEntries.Entry entries = 6;</code>
       */
      public com.reber.raft.AppendEntriesProtos.AppendEntries.EntryOrBuilder getEntriesOrBuilder(
          int index) {
        if (entriesBuilder_ == null) {
          return entries_.get(index);  } else {
          return entriesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .raft.AppendEntries.Entry entries = 6;</code>
       */
      public java.util.List<? extends com.reber.raft.AppendEntriesProtos.AppendEntries.EntryOrBuilder> 
           getEntriesOrBuilderList() {
        if (entriesBuilder_ != null) {
          return entriesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(entries_);
        }
      }
      /**
       * <code>repeated .raft.AppendEntries.Entry entries = 6;</code>
       */
      public com.reber.raft.AppendEntriesProtos.AppendEntries.Entry.Builder addEntriesBuilder() {
        return getEntriesFieldBuilder().addBuilder(
            com.reber.raft.AppendEntriesProtos.AppendEntries.Entry.getDefaultInstance());
      }
      /**
       * <code>repeated .raft.AppendEntries.Entry entries = 6;</code>
       */
      public com.reber.raft.AppendEntriesProtos.AppendEntries.Entry.Builder addEntriesBuilder(
          int index) {
        return getEntriesFieldBuilder().addBuilder(
            index, com.reber.raft.AppendEntriesProtos.AppendEntries.Entry.getDefaultInstance());
      }
      /**
       * <code>repeated .raft.AppendEntries.Entry entries = 6;</code>
       */
      public java.util.List<com.reber.raft.AppendEntriesProtos.AppendEntries.Entry.Builder> 
           getEntriesBuilderList() {
        return getEntriesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.reber.raft.AppendEntriesProtos.AppendEntries.Entry, com.reber.raft.AppendEntriesProtos.AppendEntries.Entry.Builder, com.reber.raft.AppendEntriesProtos.AppendEntries.EntryOrBuilder> 
          getEntriesFieldBuilder() {
        if (entriesBuilder_ == null) {
          entriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.reber.raft.AppendEntriesProtos.AppendEntries.Entry, com.reber.raft.AppendEntriesProtos.AppendEntries.Entry.Builder, com.reber.raft.AppendEntriesProtos.AppendEntries.EntryOrBuilder>(
                  entries_,
                  ((bitField0_ & 0x00000020) == 0x00000020),
                  getParentForChildren(),
                  isClean());
          entries_ = null;
        }
        return entriesBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:raft.AppendEntries)
    }

    // @@protoc_insertion_point(class_scope:raft.AppendEntries)
    private static final com.reber.raft.AppendEntriesProtos.AppendEntries DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.reber.raft.AppendEntriesProtos.AppendEntries();
    }

    public static com.reber.raft.AppendEntriesProtos.AppendEntries getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<AppendEntries>
        PARSER = new com.google.protobuf.AbstractParser<AppendEntries>() {
      public AppendEntries parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AppendEntries(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AppendEntries> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AppendEntries> getParserForType() {
      return PARSER;
    }

    public com.reber.raft.AppendEntriesProtos.AppendEntries getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_raft_AppendEntries_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_raft_AppendEntries_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_raft_AppendEntries_Entry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_raft_AppendEntries_Entry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023AppendEntries.proto\022\004raft\"\312\001\n\rAppendEn" +
      "tries\022\014\n\004term\030\001 \001(\005\022\020\n\010leaderId\030\002 \001(\t\022\024\n" +
      "\014prevLogIndex\030\003 \001(\005\022\023\n\013prevLogterm\030\004 \001(\005" +
      "\022\024\n\014leaderCommit\030\005 \001(\005\022*\n\007entries\030\006 \003(\0132" +
      "\031.raft.AppendEntries.Entry\032,\n\005Entry\022\022\n\nt" +
      "ermNumber\030\001 \001(\005\022\017\n\007message\030\002 \001(\tB%\n\016com." +
      "reber.raftB\023AppendEntriesProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_raft_AppendEntries_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_raft_AppendEntries_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_raft_AppendEntries_descriptor,
        new java.lang.String[] { "Term", "LeaderId", "PrevLogIndex", "PrevLogterm", "LeaderCommit", "Entries", });
    internal_static_raft_AppendEntries_Entry_descriptor =
      internal_static_raft_AppendEntries_descriptor.getNestedTypes().get(0);
    internal_static_raft_AppendEntries_Entry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_raft_AppendEntries_Entry_descriptor,
        new java.lang.String[] { "TermNumber", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
