// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RequestVote.proto

package com.reber.raft;

public final class RequestVoteProtos {
  private RequestVoteProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestVoteOrBuilder extends
      // @@protoc_insertion_point(interface_extends:raft.RequestVote)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 term = 1;</code>
     */
    boolean hasTerm();
    /**
     * <code>optional int32 term = 1;</code>
     */
    int getTerm();

    /**
     * <code>optional string candidateId = 2;</code>
     */
    boolean hasCandidateId();
    /**
     * <code>optional string candidateId = 2;</code>
     */
    java.lang.String getCandidateId();
    /**
     * <code>optional string candidateId = 2;</code>
     */
    com.google.protobuf.ByteString
        getCandidateIdBytes();

    /**
     * <code>optional int32 lastLogIndex = 3;</code>
     */
    boolean hasLastLogIndex();
    /**
     * <code>optional int32 lastLogIndex = 3;</code>
     */
    int getLastLogIndex();

    /**
     * <code>optional int32 lastLogTerm = 4;</code>
     */
    boolean hasLastLogTerm();
    /**
     * <code>optional int32 lastLogTerm = 4;</code>
     */
    int getLastLogTerm();
  }
  /**
   * Protobuf type {@code raft.RequestVote}
   */
  public  static final class RequestVote extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:raft.RequestVote)
      RequestVoteOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RequestVote.newBuilder() to construct.
    private RequestVote(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestVote() {
      term_ = 0;
      candidateId_ = "";
      lastLogIndex_ = 0;
      lastLogTerm_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RequestVote(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              term_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              candidateId_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              lastLogIndex_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              lastLogTerm_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.reber.raft.RequestVoteProtos.internal_static_raft_RequestVote_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.reber.raft.RequestVoteProtos.internal_static_raft_RequestVote_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.reber.raft.RequestVoteProtos.RequestVote.class, com.reber.raft.RequestVoteProtos.RequestVote.Builder.class);
    }

    private int bitField0_;
    public static final int TERM_FIELD_NUMBER = 1;
    private int term_;
    /**
     * <code>optional int32 term = 1;</code>
     */
    public boolean hasTerm() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 term = 1;</code>
     */
    public int getTerm() {
      return term_;
    }

    public static final int CANDIDATEID_FIELD_NUMBER = 2;
    private volatile java.lang.Object candidateId_;
    /**
     * <code>optional string candidateId = 2;</code>
     */
    public boolean hasCandidateId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string candidateId = 2;</code>
     */
    public java.lang.String getCandidateId() {
      java.lang.Object ref = candidateId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          candidateId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string candidateId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCandidateIdBytes() {
      java.lang.Object ref = candidateId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        candidateId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LASTLOGINDEX_FIELD_NUMBER = 3;
    private int lastLogIndex_;
    /**
     * <code>optional int32 lastLogIndex = 3;</code>
     */
    public boolean hasLastLogIndex() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 lastLogIndex = 3;</code>
     */
    public int getLastLogIndex() {
      return lastLogIndex_;
    }

    public static final int LASTLOGTERM_FIELD_NUMBER = 4;
    private int lastLogTerm_;
    /**
     * <code>optional int32 lastLogTerm = 4;</code>
     */
    public boolean hasLastLogTerm() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 lastLogTerm = 4;</code>
     */
    public int getLastLogTerm() {
      return lastLogTerm_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, term_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, candidateId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, lastLogIndex_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, lastLogTerm_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, term_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, candidateId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, lastLogIndex_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, lastLogTerm_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.reber.raft.RequestVoteProtos.RequestVote)) {
        return super.equals(obj);
      }
      com.reber.raft.RequestVoteProtos.RequestVote other = (com.reber.raft.RequestVoteProtos.RequestVote) obj;

      boolean result = true;
      result = result && (hasTerm() == other.hasTerm());
      if (hasTerm()) {
        result = result && (getTerm()
            == other.getTerm());
      }
      result = result && (hasCandidateId() == other.hasCandidateId());
      if (hasCandidateId()) {
        result = result && getCandidateId()
            .equals(other.getCandidateId());
      }
      result = result && (hasLastLogIndex() == other.hasLastLogIndex());
      if (hasLastLogIndex()) {
        result = result && (getLastLogIndex()
            == other.getLastLogIndex());
      }
      result = result && (hasLastLogTerm() == other.hasLastLogTerm());
      if (hasLastLogTerm()) {
        result = result && (getLastLogTerm()
            == other.getLastLogTerm());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTerm()) {
        hash = (37 * hash) + TERM_FIELD_NUMBER;
        hash = (53 * hash) + getTerm();
      }
      if (hasCandidateId()) {
        hash = (37 * hash) + CANDIDATEID_FIELD_NUMBER;
        hash = (53 * hash) + getCandidateId().hashCode();
      }
      if (hasLastLogIndex()) {
        hash = (37 * hash) + LASTLOGINDEX_FIELD_NUMBER;
        hash = (53 * hash) + getLastLogIndex();
      }
      if (hasLastLogTerm()) {
        hash = (37 * hash) + LASTLOGTERM_FIELD_NUMBER;
        hash = (53 * hash) + getLastLogTerm();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.reber.raft.RequestVoteProtos.RequestVote parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reber.raft.RequestVoteProtos.RequestVote parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reber.raft.RequestVoteProtos.RequestVote parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reber.raft.RequestVoteProtos.RequestVote parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reber.raft.RequestVoteProtos.RequestVote parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reber.raft.RequestVoteProtos.RequestVote parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reber.raft.RequestVoteProtos.RequestVote parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.reber.raft.RequestVoteProtos.RequestVote parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.reber.raft.RequestVoteProtos.RequestVote parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.reber.raft.RequestVoteProtos.RequestVote parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.reber.raft.RequestVoteProtos.RequestVote parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.reber.raft.RequestVoteProtos.RequestVote parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.reber.raft.RequestVoteProtos.RequestVote prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code raft.RequestVote}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:raft.RequestVote)
        com.reber.raft.RequestVoteProtos.RequestVoteOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.reber.raft.RequestVoteProtos.internal_static_raft_RequestVote_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.reber.raft.RequestVoteProtos.internal_static_raft_RequestVote_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.reber.raft.RequestVoteProtos.RequestVote.class, com.reber.raft.RequestVoteProtos.RequestVote.Builder.class);
      }

      // Construct using com.reber.raft.RequestVoteProtos.RequestVote.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        term_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        candidateId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        lastLogIndex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        lastLogTerm_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.reber.raft.RequestVoteProtos.internal_static_raft_RequestVote_descriptor;
      }

      public com.reber.raft.RequestVoteProtos.RequestVote getDefaultInstanceForType() {
        return com.reber.raft.RequestVoteProtos.RequestVote.getDefaultInstance();
      }

      public com.reber.raft.RequestVoteProtos.RequestVote build() {
        com.reber.raft.RequestVoteProtos.RequestVote result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.reber.raft.RequestVoteProtos.RequestVote buildPartial() {
        com.reber.raft.RequestVoteProtos.RequestVote result = new com.reber.raft.RequestVoteProtos.RequestVote(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.term_ = term_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.candidateId_ = candidateId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.lastLogIndex_ = lastLogIndex_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.lastLogTerm_ = lastLogTerm_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.reber.raft.RequestVoteProtos.RequestVote) {
          return mergeFrom((com.reber.raft.RequestVoteProtos.RequestVote)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.reber.raft.RequestVoteProtos.RequestVote other) {
        if (other == com.reber.raft.RequestVoteProtos.RequestVote.getDefaultInstance()) return this;
        if (other.hasTerm()) {
          setTerm(other.getTerm());
        }
        if (other.hasCandidateId()) {
          bitField0_ |= 0x00000002;
          candidateId_ = other.candidateId_;
          onChanged();
        }
        if (other.hasLastLogIndex()) {
          setLastLogIndex(other.getLastLogIndex());
        }
        if (other.hasLastLogTerm()) {
          setLastLogTerm(other.getLastLogTerm());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.reber.raft.RequestVoteProtos.RequestVote parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.reber.raft.RequestVoteProtos.RequestVote) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int term_ ;
      /**
       * <code>optional int32 term = 1;</code>
       */
      public boolean hasTerm() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 term = 1;</code>
       */
      public int getTerm() {
        return term_;
      }
      /**
       * <code>optional int32 term = 1;</code>
       */
      public Builder setTerm(int value) {
        bitField0_ |= 0x00000001;
        term_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 term = 1;</code>
       */
      public Builder clearTerm() {
        bitField0_ = (bitField0_ & ~0x00000001);
        term_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object candidateId_ = "";
      /**
       * <code>optional string candidateId = 2;</code>
       */
      public boolean hasCandidateId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string candidateId = 2;</code>
       */
      public java.lang.String getCandidateId() {
        java.lang.Object ref = candidateId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            candidateId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string candidateId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCandidateIdBytes() {
        java.lang.Object ref = candidateId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          candidateId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string candidateId = 2;</code>
       */
      public Builder setCandidateId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        candidateId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string candidateId = 2;</code>
       */
      public Builder clearCandidateId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        candidateId_ = getDefaultInstance().getCandidateId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string candidateId = 2;</code>
       */
      public Builder setCandidateIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        candidateId_ = value;
        onChanged();
        return this;
      }

      private int lastLogIndex_ ;
      /**
       * <code>optional int32 lastLogIndex = 3;</code>
       */
      public boolean hasLastLogIndex() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 lastLogIndex = 3;</code>
       */
      public int getLastLogIndex() {
        return lastLogIndex_;
      }
      /**
       * <code>optional int32 lastLogIndex = 3;</code>
       */
      public Builder setLastLogIndex(int value) {
        bitField0_ |= 0x00000004;
        lastLogIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 lastLogIndex = 3;</code>
       */
      public Builder clearLastLogIndex() {
        bitField0_ = (bitField0_ & ~0x00000004);
        lastLogIndex_ = 0;
        onChanged();
        return this;
      }

      private int lastLogTerm_ ;
      /**
       * <code>optional int32 lastLogTerm = 4;</code>
       */
      public boolean hasLastLogTerm() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 lastLogTerm = 4;</code>
       */
      public int getLastLogTerm() {
        return lastLogTerm_;
      }
      /**
       * <code>optional int32 lastLogTerm = 4;</code>
       */
      public Builder setLastLogTerm(int value) {
        bitField0_ |= 0x00000008;
        lastLogTerm_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 lastLogTerm = 4;</code>
       */
      public Builder clearLastLogTerm() {
        bitField0_ = (bitField0_ & ~0x00000008);
        lastLogTerm_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:raft.RequestVote)
    }

    // @@protoc_insertion_point(class_scope:raft.RequestVote)
    private static final com.reber.raft.RequestVoteProtos.RequestVote DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.reber.raft.RequestVoteProtos.RequestVote();
    }

    public static com.reber.raft.RequestVoteProtos.RequestVote getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<RequestVote>
        PARSER = new com.google.protobuf.AbstractParser<RequestVote>() {
      public RequestVote parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RequestVote(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestVote> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RequestVote> getParserForType() {
      return PARSER;
    }

    public com.reber.raft.RequestVoteProtos.RequestVote getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_raft_RequestVote_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_raft_RequestVote_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021RequestVote.proto\022\004raft\"[\n\013RequestVote" +
      "\022\014\n\004term\030\001 \001(\005\022\023\n\013candidateId\030\002 \001(\t\022\024\n\014l" +
      "astLogIndex\030\003 \001(\005\022\023\n\013lastLogTerm\030\004 \001(\005B#" +
      "\n\016com.reber.raftB\021RequestVoteProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_raft_RequestVote_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_raft_RequestVote_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_raft_RequestVote_descriptor,
        new java.lang.String[] { "Term", "CandidateId", "LastLogIndex", "LastLogTerm", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
